const projectsData = [
    {name: "My Wallet", description: "Aplicação web para controle de finanças pessoais", 
    category: "Full-stack", repository: "my-wallet", deploy: "https://my-wallet-taupe.vercel.app/", 
    stacks: "HTML 5, CSS3, JavaScript, React, Node.js, Express, MongoDB, Mongo Atlas, Vercel, Heroku, Git, Linux"},
    {name: "TrackIt", description: "Aplicação web para gerenciamento de tarefas diárias", 
    category: "Front-end", repository: "trackIt", deploy: "https://track-it-sable.vercel.app/", 
    stacks: "HTML 5, CSS3, JavaScript, React, Vercel, Git, Linux"},
    {name: "CineFlex", description: "Aplicação web para sessões de cinema", 
    category: "Front-end", repository: "cineflex", deploy: "https://cineflex-chi.vercel.app/", 
    stacks: "HTML 5, CSS3, JavaScript, React, Vercel, Git, Linux"},
    {name: "BoardCamp", description: "Aplicação web para gerenciamento de aluguéis de jogos", 
    category: "Back-end", repository: "boardcamp", deploy: false, 
    stacks: "Node.js, Express, PostgreSQL, Git, Linux"},
    {name: "Instagram", description: "Clone da página principal do Instagram", 
    category: "Front-end", repository: "instagram-react", deploy: "https://instagram-react-two.vercel.app/", 
    stacks: "HTML 5, CSS3, JavaScript, React, Vercel, Git, Linux"},
    {name: "Bate Papo Uol", description: "Aplicação web inspirada na antiga sala de bate-papo Uol", 
    category: "Back-end", repository: "bate-papo-uol-api", deploy: false, 
    stacks: "Node.js, Express, Git, Linux"},
    {name: "Driven Eats", description: "Aplicação web mobile para fast-food", 
    category: "Front-end", repository: "projeto3-driveneats", deploy: "https://guedesclaudio.github.io/projeto3-driveneats/", 
    stacks: "HTML 5, CSS3, JavaScript, Git, Linux"},
    {name: "Globo.com", description: "Clone da página principal do Globo.com", 
    category: "Front-end", repository: "projeto1-globe.com", deploy: "https://guedesclaudio.github.io/projeto1-globe.com/", 
    stacks: "HTML 5, CSS3"},
    {name: "BuzzQuizz", description: "Aplicação web realizada em equipe com o intuito de criar um site de quizzes", 
    category: "Front-end", repository: "projeto6_buzzquizz", deploy: "https://guedesclaudio.github.io/projeto6_buzzquizz/", 
    stacks: "HTML 5, CSS3, JavaScript, Git, Linux"},
]

export default projectsData