const projectsData = [
    {name: "Manger System", description: "Aplicação web realizada para um cliente, com objetivo de ser um gerenciador de produtos e dados de clientes", 
    category: "Full-stack", repository: "managersystem-backend", deploy: false, 
    stacks: "JavaScript, React, Node.js, Express, PosgreSQL, Vercel, Render, Git, Linux"},
    {name: "Linkr", description: "Aplicação web para uma rede social de compartilhamento de links", 
    category: "Full-stack", repository: "linkr-front", deploy: "http://linkr-gules-sigma.vercel.app/", obs: "Deploy temporariamente indisponível, clique no ícone do git-hub para acessar o código fonte", 
    stacks: "JavaScript, React, Node.js, Express, PosgreSQL, Vercel, Heroku, Git, Linux"},
    {name: "My Wallet", description: "Aplicação web para controle de finanças pessoais", 
    category: "Full-stack", repository: "my-wallet", deploy: "https://my-wallet-taupe.vercel.app/", obs: "Deploy temporariamente indisponível, clique no ícone do git-hub para acessar o código fonte", 
    stacks: "JavaScript, React, Node.js, Express, MongoDB, Mongo Atlas, Vercel, Heroku, Git, Linux"},
    {name: "TrackIt", description: "Aplicação web para gerenciamento de tarefas diárias", 
    category: "Front-end", repository: "trackIt", deploy: "https://track-it-sable.vercel.app/", 
    stacks: "HTML 5, CSS3, JavaScript, React, Vercel, Git, Linux"},
    {name: "CineFlex", description: "Aplicação web para sessões de cinema", 
    category: "Front-end", repository: "cineflex", deploy: "https://cineflex-chi.vercel.app/", 
    stacks: "HTML 5, CSS3, JavaScript, React, Vercel, Git, Linux"},
    {name: "BoardCamp", description: "Aplicação web para gerenciamento de aluguéis de jogos", 
    category: "Back-end", repository: "boardcamp", deploy: false, 
    stacks: "Node.js, Express, PostgreSQL, Git, Linux"},
    {name: "Instagram", description: "Clone da página principal do Instagram", 
    category: "Front-end", repository: "instagram-react", deploy: "https://instagram-react-two.vercel.app/", 
    stacks: "HTML 5, CSS3, JavaScript, React, Vercel, Git, Linux"},
    {name: "Globo.com", description: "Clone da página principal do Globo.com", 
    category: "Front-end", repository: "projeto1-globe.com", deploy: "https://guedesclaudio.github.io/projeto1-globe.com/", 
    stacks: "HTML 5, CSS3"},
    {name: "BuzzQuizz", description: "Aplicação web realizada para criação de quizz", 
    category: "Front-end", repository: "projeto6_buzzquizz", deploy: "https://guedesclaudio.github.io/projeto6_buzzquizz/", 
    stacks: "HTML 5, CSS3, JavaScript, Git, Linux"},
]

export default projectsData